// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://vtfufzzedwevcgplipyi.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6InZ0ZnVmenplZHdldmNncGxpcHlpIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NTE2NTc3NDUsImV4cCI6MjA2NzIzMzc0NX0.6wax4j02YYPlRh1XUTn9i9BawRfTtKMlb8hhFhhDJ6U";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY, {
  auth: {
    storage: localStorage,
    persistSession: true,
    autoRefreshToken: true,
  }
});